baseURL = 'https://ronardgpana.github.io/'
title = 'Ronard Paña'

# multi-language support
defaultContentLanguage = 'en'

# enable git info
enableGitInfo = true

# disable taxonomy, term and RSS (which removes categories, tags and index.xml)
disableKinds = ["taxonomy", "term", "RSS"]

[module]
  [[module.imports]]
    path = 'github.com/geekifan/zero-academic-page'

[languages]
  [languages.en]
    languageName = 'English'
    weight = 1
    title = 'Zero'

    [languages.en.params]
      author = "Ronard G. Paña"
      description = "Ph.D. Candidate, Energy Engineering. Focusing on applied reinforcement learning for energy systems."
    
    [[languages.en.menu.main]]
      name = 'About Me'
      url = '#about-me'
      weight = 1
    [[languages.en.menu.main]]
      name = 'News'
      url = '#news'
      weight = 2
    [[languages.en.menu.main]]
      name = 'Publications'
      url = '#publications'
      weight = 3
    [[languages.en.menu.main]]
      name = 'Work Experience'
      url = '#work-experience'
      weight = 4
    [[languages.en.menu.main]]
      name = 'Education'
      url = '#education'
      weight = 5
    [[languages.en.menu.main]]
      name = 'Conferences'
      url = '#conferences'
      weight = 6
    [[languages.en.menu.main]]
      name = 'Projects'
      url = '#projects'
      weight = 7

[params]
  profilePicture = "images/profile_pana.jpg"
  enableDarkMode = true
  
  [[params.social]]
    name = "github"
    url = "https://github.com/ronardgpana/"
    icon = "fab fa-github"
  [[params.social]]
    name = "google-scholar"
    url = "https://scholar.google.com/citations?hl=en&user=0XUtNegAAAAJ/"
    icon = "fab fa-google-scholar"
  [[params.social]]
    name = "email"
    url = "mailto:ronard.pana@vsu.edu.ph"
    icon = "fas fa-envelope"
  [[params.social]]
    name = "linkedin"
    url = "https://www.linkedin.com/in/ronardpana/"
    icon = "fab fa-linkedin"
  [[params.social]]
    name = "researchgate"
    url = "https://www.researchgate.net/profile/Ronard-Pana-2?ev=hdr_xprf"
    icon = "fab fa-researchgate"

[build]
  writeStats = false

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
